import { Poppins } from "next/font/google";

import type { Metadata } from "next";

import "./globals.css";
import { Navbar } from "@/components/atoms/navbar";
import { Footer } from "@/components/organisms/footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--poppins-font",
});

export const metadata: Metadata = {
  title: "Serwis Blacharsko Lakierniczy | IMPORTOWO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className}`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
